AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  APIGateway

  Sample SAM Template for APIGateway
Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function  
    Properties:
      CodeUri: DynamoDB_CRUD/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        BooksGet:
          Type: Api 
          Properties:
            Path: /books
            Method: get
        BooksGetSpec:
          Type: Api
          Properties:
            Path: /books/{id}
            Method: get
        BooksPost:
          Type: Api
          Properties:
            Path: /books
            Method: post
        BooksPut:
          Type: Api
          Properties:
            Path: /books/{id}
            Method: put
        BooksDelete:
          Type: Api
          Properties:
            Path: /books/{id}
            Method: delete
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BooksDynamoDB 
  BooksDynamoDB:
    Type: AWS::Serverless::SimpleTable  
    Properties:
      TableName: my-table
      PrimaryKey:
          Name: id
          Type: String
      ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/books/"
